# Generated by Django 6.1 on 2026-08-08 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='ООО СОЛНЕЧНЫЙ МЕЧ', max_length=200, verbose_name='Название компании')),
                ('brand_name', models.CharField(default='УБИРАЕМСЯЛЕГКО', max_length=100, verbose_name='Бренд')),
                ('slogan', models.CharField(default='Что-то не отмывается, просто скажите', max_length=255, verbose_name='Слоган')),
                ('tagline', models.CharField(default='профессиональные моющие средства для дома и организаций', max_length=255, verbose_name='Подзаголовок')),
                ('phone', models.CharField(default='8-991-496-18-97', max_length=40, verbose_name='Телефон')),
                ('email', models.EmailField(default='pro-brite_uss@mail.ru', max_length=254, verbose_name='Email')),
                ('order_email', models.EmailField(default='pro-brite_uss@mail.ru', max_length=254, verbose_name='Email для заявок')),
                ('city', models.CharField(default='г. Уссурийск', max_length=100, verbose_name='Город')),
                ('address', models.CharField(default='ул. Горького 91, ст4 (вход с ул. Амурская)', max_length=300, verbose_name='Адрес')),
                ('full_address', models.CharField(default='Приморский край, г. Уссурийск, ул. Горького 91, ст4, магазин «Убираемсялегко»', max_length=400, verbose_name='Полный адрес')),
                ('working_hours', models.CharField(default='с 9.00 до 20.00 (без выходных)', max_length=100, verbose_name='Часы работы')),
                ('inn', models.CharField(default='2511130194', max_length=20, verbose_name='ИНН')),
                ('ogrn', models.CharField(default='1242500027120', max_length=20, verbose_name='ОГРН')),
                ('max_channel_url', models.URLField(blank=True, verbose_name='Ссылка на канал MAX')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
