# Generated by Django 6.1 on 2026-08-08 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Город')),
                ('region', models.CharField(blank=True, default='Приморский край', max_length=120, verbose_name='Регион')),
                ('is_default', models.BooleanField(default=False, verbose_name='По умолчанию')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='city',
            field=models.CharField(default='г. Уссурийск', max_length=100, verbose_name='Город (текст в футере)'),
        ),
    ]
