# Generated by Django 6.1 on 2026-08-09 04:19

from django.db import migrations, models

MAX_URL = 'https://max.ru/join/5n4w4WgqNIhX-fh4J5fjF5-NeJ_q728An7crUD3gF08'


def fill_max_channel_url(apps, schema_editor):
    SiteSettings = apps.get_model('core', 'SiteSettings')
    SiteSettings.objects.filter(max_channel_url='').update(max_channel_url=MAX_URL)
    if not SiteSettings.objects.exists():
        SiteSettings.objects.create(pk=1, max_channel_url=MAX_URL)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_city_alter_sitesettings_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='max_channel_url',
            field=models.URLField(blank=True, default=MAX_URL, verbose_name='Ссылка на канал MAX'),
        ),
        migrations.RunPython(fill_max_channel_url, noop),
    ]
