# Generated by Django 6.1 on 2026-08-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_site_settings_max_channel_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='note',
            field=models.CharField(blank=True, help_text='Например: «Доставка в другие города»', max_length=200, verbose_name='Подпись'),
        ),
    ]
