# Generated by Django 6.1

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_productimage_image_card'),
        ('core', '0006_move_stainhelprequest_to_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_key', models.CharField(db_index=True, max_length=64, verbose_name='Посетитель')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Когда')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Статистика',
                'verbose_name_plural': 'Статистика',
                'indexes': [
                    models.Index(fields=['viewed_at', 'product'], name='core_produc_viewed__7a1e2a_idx'),
                    models.Index(fields=['product', 'visitor_key', 'viewed_at'], name='core_produc_product_8c4f1b_idx'),
                ],
            },
        ),
    ]
