# Generated by Django 6.1 on 2026-08-29 01:28

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0012_sitevisit_ip_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchStatistics',
            fields=[
            ],
            options={
                'verbose_name': 'По поиску',
                'verbose_name_plural': 'По поиску',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.searchquerylog',),
        ),
        migrations.CreateModel(
            name='SiteStatistics',
            fields=[
            ],
            options={
                'verbose_name': 'По сайту',
                'verbose_name_plural': 'По сайту',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.productpageview',),
        ),
    ]
