# Generated by Django 6.1 on 2026-08-09 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_delivery_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryaddress',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
