# Generated by Django 6.1 on 2026-09-04

from django.db import migrations, models
from django.db.models import Max


def backfill_last_site_visit(apps, schema_editor):
    from django.db.models.functions import Coalesce

    Profile = apps.get_model('accounts', 'Profile')
    SiteVisit = apps.get_model('core', 'SiteVisit')

    visits = (
        SiteVisit.objects.filter(visitor_key__startswith='u:')
        .values('visitor_key')
        .annotate(last_at=Coalesce(Max('last_hit_at'), Max('visited_at')))
    )
    for row in visits:
        key = row['visitor_key'] or ''
        try:
            user_id = int(key.split(':', 1)[1])
        except (IndexError, ValueError, TypeError):
            continue
        if row['last_at'] is None:
            continue
        Profile.objects.filter(user_id=user_id).update(last_site_visit_at=row['last_at'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delivery_address_name_no_help'),
        ('core', '0014_sitevisit_freeze_ddos'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_site_visit_at',
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name='Последний вход на сайт',
            ),
        ),
        migrations.RunPython(backfill_last_site_visit, migrations.RunPython.noop),
    ]
