# Generated by Django 5.x

from django.db import migrations


def seed_default_groups(apps, schema_editor):
    # Импорт после apps ready: Permission/Group через ORM приложения
    from accounts.roles import ensure_default_groups

    ensure_default_groups()


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_last_site_visit_at'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cart', '0008_stainhelprequest'),
    ]

    operations = [
        migrations.RunPython(seed_default_groups, noop_reverse),
    ]
