# Generated by Django 6.1 on 2026-08-09 06:13

from decimal import Decimal

from django.db import migrations, models
from django.db.models import Avg, Count


def recalculate_ratings(apps, schema_editor):
    Product = apps.get_model('catalog', 'Product')
    ProductReview = apps.get_model('catalog', 'ProductReview')
    for product in Product.objects.all().iterator():
        agg = ProductReview.objects.filter(product_id=product.pk).aggregate(
            avg=Avg('rating'),
            cnt=Count('id'),
        )
        count = int(agg['cnt'] or 0)
        if count == 0 or agg['avg'] is None:
            Product.objects.filter(pk=product.pk).update(rating=Decimal('0'), reviews_count=0)
        else:
            Product.objects.filter(pk=product.pk).update(
                rating=Decimal(str(round(float(agg['avg']), 1))),
                reviews_count=count,
            )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reviews_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Число оценок'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=3, verbose_name='Рейтинг'),
        ),
        migrations.RunPython(recalculate_ratings, noop_reverse),
    ]
