# Generated by Django 6.1 on 2026-08-09 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_rating_default_and_reviews_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Ед. измерения'),
        ),
    ]
