# Generated by Django 6.1 on 2026-08-09 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'Фото', 'verbose_name_plural': 'Фото'},
        ),
    ]
