# Generated by Django 6.1 on 2026-08-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_remove_product_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='recommendation_codes',
            field=models.CharField(
                blank=True,
                default='',
                help_text=(
                    'Номера групп через запятую, например: 1 или 1,3,5. '
                    'Товары с общим номером показываются друг другу в рекомендациях на сайте.'
                ),
                max_length=100,
                verbose_name='Рекомендация',
            ),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(
                choices=[
                    ('in_stock', 'В\xa0наличии'),
                    ('in_transit', 'В\xa0пути'),
                    ('out_of_stock', 'Нет\xa0в\xa0наличии'),
                    ('on_order', 'Под\xa0заказ'),
                ],
                default='in_stock',
                max_length=20,
                verbose_name='Статус',
            ),
        ),
    ]
