# Generated by Django 6.1 on 2026-08-14 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_clear_promo_without_old_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_card',
            field=models.ImageField(blank=True, editable=False, help_text='Автоматически создаётся из главного фото для быстрой загрузки каталога', upload_to='products/cards/', verbose_name='Превью для каталога'),
        ),
    ]
