# Generated by Django 6.1 on 2026-08-16 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_productimage_image_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='seo_description',
            field=models.CharField(blank=True, default='', help_text='Если пусто — описание из семантического ядра категории', max_length=320, verbose_name='SEO description'),
        ),
        migrations.AddField(
            model_name='category',
            name='seo_text',
            field=models.TextField(blank=True, default='', help_text='Дополнительный текст под товарами категории (для поисковиков)', verbose_name='SEO-текст на странице'),
        ),
        migrations.AddField(
            model_name='category',
            name='seo_title',
            field=models.CharField(blank=True, default='', help_text='Если пусто — подставится шаблон с названием категории', max_length=255, verbose_name='SEO title'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_description',
            field=models.CharField(blank=True, default='', help_text='Если пусто — начало описания товара', max_length=320, verbose_name='SEO description'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_title',
            field=models.CharField(blank=True, default='', help_text='Если пусто — «{название} — купить в Уссурийске | бренд»', max_length=255, verbose_name='SEO title'),
        ),
    ]
