# Generated by Django 6.1 on 2026-08-16 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_category_product_seo_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='seo_description',
            field=models.CharField(blank=True, default='', help_text='Только для поисковиков (meta description). На витрине не показывается.', max_length=320, verbose_name='SEO description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='seo_text',
            field=models.TextField(blank=True, default='', help_text='Доп. текст только для meta description, если SEO description пустой. На странице сайта посетителям не показывается.', verbose_name='SEO-текст (для meta)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='seo_title',
            field=models.CharField(blank=True, default='', help_text='Только для поисковиков (тег title). На витрине не показывается. Пусто — автошаблон.', max_length=255, verbose_name='SEO title'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seo_description',
            field=models.CharField(blank=True, default='', help_text='Только для поисковиков (meta description). На витрине не показывается.', max_length=320, verbose_name='SEO description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seo_title',
            field=models.CharField(blank=True, default='', help_text='Только для поисковиков (тег title). На витрине не показывается.', max_length=255, verbose_name='SEO title'),
        ),
    ]
