# Generated by Django 6.1 on 2026-08-09 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('courier', 'Курьером'), ('pickup', 'Самовывоз')], default='courier', max_length=20, verbose_name='Способ получения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='Имя'),
        ),
    ]
