# Generated by Django 6.1 on 2026-08-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_order_delivery_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название адреса'),
        ),
    ]
